project:
  type: website
  output-dir: docs

website:
  title: "dashboards"
  navbar:
    left:
      - href: https://vladtomutiu.github.io
        text: Website
      - href: visualizations.qmd
        text: visualizations

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

